# NumPy
***

### Numerical Python
***

- Numpy used for scientific calculations.
- Numpy used for working with arrays.

#### Import

In [31]:
import numpy as np

In [32]:
import numpy as np 
x=np.array([12,3,5,2])
x

array([12,  3,  5,  2])

#### Creating Array
***

In [34]:
import numpy as np
np.zeros((2,3),int)  #consisting of zeros [2,3] matrix

array([[0, 0, 0],
       [0, 0, 0]])

In [35]:
import numpy as np
np.full((5,6),2)     #consisting of a given number [a b] matrix

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [36]:
import numpy as np
np.arange(2,10,2)    # Array from 2 to 10 increasing by two

array([2, 4, 6, 8])

In [37]:
import numpy as np
np.linspace(1,10,5)  # five numbers from 1 to 10

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [38]:
import numpy as np
np.random.normal(10,1,(2,3)) #average 10,standart deviation 1 

array([[10.9284522 , 11.31564779,  9.64203061],
       [ 8.92572534,  9.2340288 ,  9.62756529]])

In [39]:
import numpy as np
np.random.randint(1,10,(3,3)) #random numbers from 1 to 10 

array([[8, 3, 5],
       [1, 4, 1],
       [1, 1, 4]])

####  Properties
***

* **ndim()**:Dimensions
* **shape()**:The shape of an array is the number of elements in each dimension.
* **size()**:Number of elements in the array
* **dtype()**:Array type

In [42]:
import numpy as np
x=np.random.randint(1,10,size=(3,4))
print(x)
x.ndim

[[6 5 7 6]
 [6 2 5 7]
 [2 1 2 8]]


2

In [43]:
x.shape

(3, 4)

In [44]:
x.size

12

In [45]:
x.dtype

dtype('int32')

In [46]:
import numpy as np
a=np.arange(1,10,2)
a.reshape((5,1))         #Reshaping means changing the shape of an array.

array([[1],
       [3],
       [5],
       [7],
       [9]])

#### Concatenation
***
Putting contents of two or more arrays in a single array.

In [48]:
import numpy as np
x =np.array([1,2,3])
y =np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [49]:
import numpy as np
x =np.array([[1,2,3],[10,11,12]])
y =np.array([[4,5,6],[20,21,22]])
np.concatenate([x,y])

array([[ 1,  2,  3],
       [10, 11, 12],
       [ 4,  5,  6],
       [20, 21, 22]])

In [50]:
import numpy as np
x =np.array([[1,2,3],[10,11,12]])
y =np.array([[4,5,6],[20,21,22]])
np.concatenate([x,y],axis=1)   #axis=0 rows,axis=1 columns

array([[ 1,  2,  3,  4,  5,  6],
       [10, 11, 12, 20, 21, 22]])

#### Splitting
***
Splitting is reverse operation of Joining.

In [52]:
import numpy as np
x=np.array([1,2,3,7,8,9,4,5,6])
a,b,c =np.split(x,[3,6])        # from 3 to 6
a 

array([1, 2, 3])

In [53]:
b

array([7, 8, 9])

In [276]:
import numpy as np
x=np.array([[1,2,3],[4,5,6]])
top,bottom = np.vsplit(x,[1])       #split rows
top

array([[1, 2, 3]])

In [55]:
import numpy as np
x=np.array([[1,2,3,4],[4,5,6,7]])
right,left=np.hsplit(x,[1])         #split columns
right

array([[1],
       [4]])

#### Sorting
***


Used to make ordered array

In [265]:
import numpy as np
x=np.array([4,3,2,1,5])
np.sort(x)                     
#This method returns a copy of the array, leaving the original array unchanged.

array([1, 2, 3, 4, 5])

In [267]:
x.sort()                     
x
#Main array changes.

array([1, 2, 3, 4, 5])

In [101]:
import numpy as np
y=np.random.normal(5,2,(3,3))
y

array([[7.69049735, 5.34737917, 6.11421012],
       [4.81466523, 1.41117796, 6.15147581],
       [5.42756136, 4.56797002, 4.96209092]])

In [103]:
np.sort(y,axis=0)    #sort by columns

array([[4.81466523, 1.41117796, 4.96209092],
       [5.42756136, 4.56797002, 6.11421012],
       [7.69049735, 5.34737917, 6.15147581]])

In [269]:
np.sort(y,axis=1)    #sort by rows

array([[5.34737917, 6.11421012, 7.69049735],
       [1.41117796, 4.81466523, 6.15147581],
       [4.56797002, 4.96209092, 5.42756136]])

#### Access elements with Index
***

In [111]:
x=np.random.randint(1,10,size=(3,3))
x

array([[9, 3, 3],
       [5, 2, 6],
       [6, 9, 6]])

In [115]:
x[2,1]

9

In [121]:
x[2,1]=5.8
x

array([[9, 3, 3],
       [5, 2, 6],
       [6, 5, 6]])

#### Slicing
***
Used to creating subsets of array.

In [149]:
x=np.random.randint(1,10,(4,4))
x

array([[5, 5, 6, 7],
       [5, 2, 7, 4],
       [8, 5, 6, 3],
       [9, 6, 8, 7]])

In [137]:
x[0:2,1:3]             #Select between 0:2 rows,1:3 colummns

array([[5, 4],
       [9, 3]])

- copy()
***
It makes the selected subset indipendent from the main set

In [278]:
y_set=np.random.randint(10,size=(4,4))
y_set

array([[9, 1, 0, 9],
       [1, 1, 2, 6],
       [2, 2, 4, 2],
       [4, 9, 2, 7]])

In [280]:
bottom_set_y=y_set[0:3,0:2].copy()  #main set unchanged
bottom_set_y

array([[9, 1],
       [1, 1],
       [2, 2]])

In [282]:
bottom_set_y[2,0]=11111
bottom_set_y

array([[    9,     1],
       [    1,     1],
       [11111,     2]])

In [284]:
y_set

array([[9, 1, 0, 9],
       [1, 1, 2, 6],
       [2, 2, 4, 2],
       [4, 9, 2, 7]])

#### Conditional Element Operations with Fancy
***

In [236]:
t_set=np.arange(1,20,2)
t_set

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [244]:
t_set%2==1            #bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [246]:
t_kume[t_kume<10]      #condition elemenets

array([1, 3, 5, 7, 9])

#### Solving an Equation with Two Unknowns
***

In [256]:
a=np.array([[3,2],[4,2]])
b=np.array([22,12])
x=np.linalg.solve(a,b)
x

array([-10.,  26.])